name: Build / Run

on:
  workflow_call:
    inputs:
      build-args:
        required: false
        type: string
      command:
        required: false
        type: string
      dockerfile:
        default: Dockerfile
        required: false
        type: string
      run:
        default: true
        required: false
        type: boolean
      target:
        required: false
        type: string

jobs:
  build:
    runs-on: self-hosted
    env:
      GH_TOKEN_BHT: ${{ secrets.GH_TOKEN_BHT }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN_BHT }}
      - name: Build the image
        uses: docker/build-push-action@v4
        with:
          build-args: ${{ inputs.build-args }}
          file: ${{ inputs.dockerfile }}
          push: false
          tags: ${{ github.event.repository.name }}:${{ github.job }}
          target: ${{ inputs.target }}
      - name: Run
        if: inputs.run == true
        run: |
          docker run --rm ${{ github.event.repository.name }}:${{ github.job }} ${{ inputs.command }}
