name: Check

on:
  workflow_call:

jobs:
  check-pr-title:      
    runs-on: self-hosted
    steps:
      - name: Validate PR title
        uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          regex: ^(build|ci|docs|feat|fix|perf|refactor|test)(\(.*?\))?:\ .*$
