name: Test coverage

on:
  workflow_call:
    inputs:
      build-args:
        required: false
        type: string
      command:
        required: false
        type: string
      coverage-catalog:
        default: /app/coverage
        required: false
        type: string
      dockerfile:
        default: Dockerfile
        required: false
        type: string
      target:
        required: false
        type: string

jobs:
  test:
    runs-on: self-hosted
    env:
      GH_TOKEN_BHT: ${{ secrets.GH_TOKEN_BHT }}
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN_BHT }}
      - name: Build the image
        uses: docker/build-push-action@v4
        with:
          build-args: ${{ inputs.build-args }}
          context: '.'
          file: ${{ inputs.dockerfile }}
          push: false
          tags: ${{ github.event.repository.name }}:${{ github.job }}
          target: ${{ inputs.target }}
      - name: Set container name
        run: |
          echo CONTAINER_NAME=${RANDOM} >> ${GITHUB_ENV}
      - name: Run
        run: |
          docker run --name=${{ env.CONTAINER_NAME }} ${{ github.event.repository.name }}:${{ github.job }} ${{ inputs.command }}
      - name: Get coverage
        if: success() || failure()
        run: |
          docker cp ${{ env.CONTAINER_NAME }}:${{ inputs.coverage-catalog }} .
      - name: Clean up
        if: success() || failure()
        run: |
          docker rm ${{ env.CONTAINER_NAME }}
      - uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: Test coverage results
          path: coverage
          retention-days: 7
