name: Deploy

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      environment-name:
        required: true
        type: string
      service-names:
        default: |
          ${{ github.event.repository.name }}
        required: false
        type: string

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          repository: Be-Health-Tech/helm-charts
          token: ${{ secrets.GH_TOKEN_BHT }}
      - name: Configure git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Update image tag
        run: |
          service_names=(
            ${{ inputs.service-names }}
          )
          for service_name in ${service_names[@]}; do
            sed -i "s~tag: .*~tag: '${{ inputs.version }}'~g" "charts/${service_name}/values.override.${{ inputs.environment-name}}.yaml"
            git add "charts/${service_name}"
            git commit -m "chore(${service_name}): update version to ${{ inputs.version }} (${{ inputs. environment-name}})"
          done
      - name: Push changes
        run: |
          git pull --rebase
          git push
