name: Build / Run

on:
  workflow_call:
    inputs:
      build-args:
        required: false
        type: string
      command:
        required: false
        type: string
      dockerfile:
        default: Dockerfile
        required: false
        type: string
      run:
        default: true
        required: false
        type: boolean
      target:
        required: false
        type: string

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GH_TOKEN_BHT }}
      - name: Build the image
        uses: Be-Health-Tech/docker-build-push@master
        with:
          buildArgs: ${{ inputs.build-args }}
          dockerfile: ${{ inputs.dockerfile }}
          enableBuildKit: true
          image: ${{ github.event.repository.name }}
          push: false
          tags: ${{ github.job }}
          target: ${{ inputs.target }}
      - name: Run
        if: inputs.run == true
        run: |
          docker run --rm ${{ github.event.repository.name }}:${{ github.job }} ${{ inputs.command }}
