name: Publish

on:
  workflow_call:
    inputs:
      build-args:
        type: string
        required: false
      dockerfile:
        default: Dockerfile
        type: string
        required: false
      version:
        type: string
        required: true

jobs:
  build:
    runs-on: self-hosted
    env:
      GH_TOKEN_BHT: ${{ secrets.GH_TOKEN_BHT }}
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          ref: v${{ inputs.version }}
          submodules: recursive
          token: ${{ secrets.GH_TOKEN_BHT }}
      - name: Set additional environment variables
        run: |
          echo GIT_RELEASE_HASH=$(git rev-parse HEAD) >> ${GITHUB_ENV}
      - name: Publish
        uses: Be-Health-Tech/docker-build-push@master
        with:
          buildArgs: ${{ inputs.build-args }}
          dockerfile: ${{ inputs.dockerfile }}
          enableBuildKit: true
          image: ${{ github.repository }}
          password: ${{ github.token }}
          registry: ghcr.io
          tags: ${{ inputs.version }}
          username: ${{ github.actor }}
